# https://travis-ci.org/ankitpopli1891/django-autotranslate
language:
    python
python:
    - 3.5
env:
    - TOX_ENV=dj15-py26
    - TOX_ENV=dj15-py27
    - TOX_ENV=dj16-py26
    - TOX_ENV=dj16-py27
    - TOX_ENV=dj16-py33
    - TOX_ENV=dj17-py27
    - TOX_ENV=dj17-py33
    - TOX_ENV=dj17-py34
    - TOX_ENV=dj18-py27
    - TOX_ENV=dj18-py33
    - TOX_ENV=dj18-py34
    - TOX_ENV=dj18-py35
    - TOX_ENV=dj19-py27
    - TOX_ENV=dj19-py34
    - TOX_ENV=dj19-py35
    - TOX_ENV=dj110-py27
    - TOX_ENV=dj110-py34
    - TOX_ENV=dj110-py35
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
matrix:
    fast_finish: true
branches:
    only:
        - master
