# https://travis-ci.org/ankitpopli1891/django-autotranslate
language:
    python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
env:
    - DJANGO=1.5.0
    - DJANGO=1.6.0
    - DJANGO=1.7.0
    - DJANGO=1.8.0
    - DJANGO=1.9.0
install:
    - pip install Django==$DJANGO
    - pip install -r requirements.txt
script:
    - cd tests
    - python manage.py test autotranslate
matrix:
    fast_finish: true
branches:
    only:
        - master
